### ISSUE TITLE
Document workaround for "package suggested but not available" RMD check result on Windows if used in another package

### ISSUE THREAD

**Issue by aryoda** [atheriel/rsyslog#2]
If I use the `rsyslog` package in another package by declaring a `Suggests` dependency `R CMD check --as-cran` reports:

 `Package suggested but not available: 'rsyslog'`

This is caused by the fact that the `rsyslog` pkg is only available for POSIX-enabled architectures (Linux etc.), but **not** for Windows (see `OS_type: unix` in the DESCRIPTION file).

Despite `rsyslog` being in the `Suggests` section of the DESCRIPTION file it is **not** optional as the [Writing R extensions](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#The-DESCRIPTION-file) documentation claims:
    > 1.1.3.1 Suggested packages
    > Note that someone wanting to run the examples/tests/vignettes may not have a suggested package available (and it may not even be possible to install it for that platform).

This makes CRAN releases of packages that reference `rsyslog` more complicated.
I guess currently you have to ask for an exception from the rule that `R CMD check` shall not show any findings...

It would be great to find and document a solution for this problem eg. in the README file here.

For an example of a real CRAN package that is affected by this problem see `futile.logger`:

https://github.com/zatonovo/futile.logger/issues/98#issuecomment-931788454

BTW: I think asking for an explanation and possible solutions at the r-devel mailing list could be a good starting point (I could initiate this)

**Comment by atheriel** [comment]
I'd suggest you ask the mailing list, I'm not sure what the right solution is here.

For what it's worth, this package can already be compiled on Windows, and it does pass Windows submission checks -- it just throws an error if a user actually tries to use it. So I could resubmit it to CRAN with the OS limitation removed, though it might be quite misleading for users to do so.

**Comment by atheriel** [comment]
(I'm also a past contributor to the `futile.logger` package, and I'm glad to see that someone has taken on trying to release a new version with all the fixes.)

**Comment by atheriel** [comment]
Lastly, when you submit to CRAN you can give a written explanation for why a package has a NOTE -- it's possible that you could write something like

> This package has an optional dependency on `rsyslog`, which is not available for Windows.

and they would accept it. I assume this is what the `lgrExtra` and `logger` package maintainers do to handle their `rsyslog` suggestion.

**Comment by aryoda** [comment]
> Lastly, when you submit to CRAN you can give a written explanation for why a package has a NOTE
> 
> > This package has an optional dependency on `rsyslog`, which is not available for Windows.
> 
> I assume this is what the `lgrExtra` and `logger` package maintainers do to handle their `rsyslog` suggestion.

Thanks for your hints, I think this is the easiest starting point.

I will also ask at r-devel about the proposed solution and post a link here.

Compiling the package on Windows is IMHO not necessary and could be misleading for user but if all of the above "workarounds" should not work I would come back to ask for this solution.

Thanks a lot for your input :-)

**Comment by atheriel** [comment]
I'm going to close this as my proposed solution above was confirmed acceptable when I submitted [another package that Suggests this one to CRAN](https://cran.r-project.org/package=log4r).
